<?php
// api/admin/seed_poi_lacedonia_completo.php
// Seed completo POI Lacedonia — testi IT+EN, identità, categorie.
// Usa ON DUPLICATE KEY UPDATE: idempotente, aggiorna i record esistenti.
require_once __DIR__ . '/../config/db.php';
requireAdminSession();
$db = getDB();
$results = []; $errors = [];

function upsertPoi(PDO $db, array $d, array &$results, array &$errors): void {
    try {
        $db->prepare("
            INSERT INTO points_of_interest
                (id, borough_id, category, sort_order,
                 name_it, name_en,
                 desc_it, desc_en,
                 tags)
            VALUES
                (:id, :borough_id, :category, :sort_order,
                 :name_it, :name_en,
                 :desc_it, :desc_en,
                 :tags)
            ON DUPLICATE KEY UPDATE
                category   = VALUES(category),
                sort_order = VALUES(sort_order),
                name_it    = VALUES(name_it),
                name_en    = VALUES(name_en),
                desc_it    = VALUES(desc_it),
                desc_en    = VALUES(desc_en),
                tags       = VALUES(tags)
        ")->execute($d);
        $results[] = '✅ ' . $d['name_it'];
    } catch (PDOException $e) {
        $errors[] = '❌ ' . ($d['name_it'] ?? $d['id']) . ': ' . $e->getMessage();
    }
}

$pois = [

    /* ─── SPAZI URBANI ─────────────────────────────────────────────── */

    [
        'id'         => 'piazza-de-sanctis',
        'borough_id' => 'lacedonia',
        'category'   => 'Spazi Urbani',
        'sort_order' => 1,
        'name_it'    => 'Piazza Francesco De Sanctis',
        'name_en'    => 'Piazza Francesco De Sanctis',
        'desc_it'    => 'Piazza Francesco De Sanctis è il cuore pulsante di Lacedonia, dedicata all\'illustre critico letterario e filosofo che ha lasciato un\'impronta indelebile nella cultura italiana dell\'Ottocento. La piazza ospita tre monumenti di eccezionale interesse storico e artistico: il Castello Pappacoda, fortezza rinascimentale eretta tra il 1500 e il 1501 per volere del feudatario Ferdinando Pappacoda; il Museo Diocesano San Gerardo Maiella, custode di un patrimonio spirituale e artistico straordinario; e la Chiesa di San Filippo Neri, gioiello barocco del XVII secolo, sede delle celebrazioni del Compatrono di Lacedonia. L\'imponente statua bronzea di De Sanctis, realizzata dallo scultore Vincenzo Jerace, lo raffigura in atteggiamento meditativo su un alto basamento in pietra calcarea: simbolo del legame tra il pensiero critico e le radici irpine. La piazza è il nodo identitario per eccellenza di Lacedonia: qui si svolgono le manifestazioni civili e religiose più sentite dalla comunità, le processioni patronali e la vita pubblica del borgo. Il progetto MetaBorghi ha digitalizzato l\'intera piazza in un dettagliato modello 3D navigabile, consentendo a visitatori da tutto il mondo di esplorare spazi, dettagli architettonici e strati storici anche a distanza.',
        'desc_en'    => 'Piazza Francesco De Sanctis is the beating heart of Lacedonia, named after the celebrated 19th-century literary critic and philosopher who left an indelible mark on Italian culture. The square is home to three outstanding monuments: Castello Pappacoda, a Renaissance fortress built between 1500 and 1501 by the feudal lord Ferdinando Pappacoda; the Diocesan Museum of San Gerardo Maiella, guardian of an extraordinary artistic and spiritual heritage; and the Church of San Filippo Neri, a Baroque jewel from the 17th century and home of the town\'s Co-patron celebrations. The impressive bronze statue of De Sanctis, sculpted by Vincenzo Jerace, depicts him in a meditative pose on a tall limestone pedestal — a symbol of the bond between critical thought and Irpinian roots. The square serves as the civic and cultural hub of Lacedonia, hosting the community\'s most cherished celebrations, patronal processions and the public life of the village. The MetaBorghi project has digitized the entire square into a navigable 3D model, allowing visitors from around the world to explore its spaces and historical layers remotely.',
        'tags'       => 'piazza,centro storico,Francesco De Sanctis,Castello Pappacoda,Museo Diocesano,San Filippo Neri,arte,storia',
    ],

    [
        'id'         => 'via-tagliata',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Storico',
        'sort_order' => 2,
        'name_it'    => 'Via Tagliata',
        'name_en'    => 'Via Tagliata',
        'desc_it'    => 'Via Tagliata è una delle arterie più antiche e cariche di storia di Lacedonia, importante via di comunicazione già in epoca sannitica. La sua rilevanza storica raggiunse il culmine nel 216 a.C., all\'indomani della celebre battaglia di Canne: i notabili lacedoniesi decisero di abbandonare l\'alleanza con Roma per schierarsi con Annibale, nella speranza di un radicale cambiamento degli equilibri mediterranei. La scelta si rivelò fatale. Nel 212 a.C., con la sconfitta definitiva del condottiero cartaginese, Annibale ordinò la decapitazione dei traditori proprio lungo questa strada, in un gesto di implacabile ritorsione tramandato dalla tradizione per oltre due millenni. Numerose campagne archeologiche hanno portato alla luce testimonianze dell\'antico insediamento sannitico e dei drammatici eventi delle guerre puniche. Percorrere Via Tagliata oggi significa intraprendere un viaggio nel tempo, dove ogni pietra sembra custodire memorie di battaglie, tradimenti e riconciliazioni che hanno plasmato l\'identità di Lacedonia. Il progetto MetaBorghi ha prodotto un tour virtuale a 360° con colonna sonora ambientale appositamente registrata, permettendo di immergersi nell\'atmosfera unica di questo corridoio di pietra stratificato di storia.',
        'desc_en'    => 'Via Tagliata is one of Lacedonia\'s oldest and most historically significant streets, already an important communication route during the Samnite era. Its historical importance peaked in 216 BC, following the famous Battle of Cannae: local nobles chose to abandon their alliance with Rome and side with Hannibal, hoping for a radical shift in the balance of Mediterranean power. The decision proved catastrophic. In 212 BC, as Hannibal faced final defeat, he ordered the execution of the traitors along this very road — an act of implacable retribution passed down through local tradition for over two millennia. Archaeological campaigns have uncovered evidence of the ancient Samnite settlement and the dramatic events of the Punic Wars. Walking Via Tagliata today means stepping back in time, where every stone seems to hold memories of battles, betrayals and reconciliations that shaped the identity of Lacedonia. The MetaBorghi project has produced a 360° virtual tour with specially recorded ambient audio, allowing visitors to immerse themselves in the unique atmosphere of this ancient stone corridor.',
        'tags'       => 'storia sannita,guerre puniche,Annibale,216 aC,archeologia,via storica,Età antica',
    ],

    [
        'id'         => 'piazzetta-primo-maggio',
        'borough_id' => 'lacedonia',
        'category'   => 'Panorami e Belvedere',
        'sort_order' => 3,
        'name_it'    => 'Piazzetta 1° Maggio',
        'name_en'    => 'Piazzetta 1° Maggio',
        'desc_it'    => 'Situata al margine del centro storico, la Piazzetta 1° Maggio è uno degli angoli più suggestivi di Lacedonia. La sua pavimentazione in pietra calcarea locale e gli edifici storici che la circondano creano un\'atmosfera di autentica tradizione architettonica irpina. Il punto di forza indiscusso di questo spazio urbano è la sua posizione privilegiata, che consente di godere di un panorama mozzafiato sulla valle dell\'Osento: un vasto mosaico naturale di boschi, rilievi montuosi e dolci colline che si trasforma armoniosamente con il susseguirsi delle stagioni. Le ore dell\'alba e del tramonto regalano effetti cromatici di straordinaria bellezza, con le variazioni della luce naturale che dipingono il paesaggio circostante in toni sempre diversi. Anche l\'osservazione notturna, lontana dall\'inquinamento luminoso delle città, offre un firmamento di eccezionale purezza. Questo belvedere naturale è uno dei luoghi privilegiati per la fotografia paesaggistica e per i momenti di contemplazione silenziosa che il turismo lento sa offrire. Il progetto MetaBorghi ha realizzato un tour virtuale immersivo arricchito da suoni ambientali naturali — il cinguettio degli uccelli, il fruscio del vento, i rumori di fondo tipici di questo angolo irpino — per portare l\'atmosfera della Piazzetta in ogni parte del mondo.',
        'desc_en'    => 'Located at the edge of the historic center, Piazzetta 1° Maggio is one of the most evocative corners of Lacedonia. Its local limestone paving and the historic buildings that surround it create an atmosphere of authentic Irpinian architectural tradition. The undisputed highlight of this urban space is its privileged position, which offers a breathtaking panoramic view over the Osento valley — a vast natural mosaic of forests, mountain ridges and gentle hills that transforms harmoniously with the changing seasons. The hours of dawn and sunset produce extraordinary chromatic effects, with natural light painting the surrounding landscape in ever-changing tones. After dark, far from urban light pollution, the night sky offers exceptional clarity. This natural belvedere is one of the most prized spots for landscape photography and the silent contemplation that slow tourism affords. The MetaBorghi project has created an immersive virtual tour enriched with natural ambient sounds — birdsong, rustling wind, and the characteristic background sounds of this Irpinian corner — to bring the atmosphere of the Piazzetta to every corner of the world.',
        'tags'       => 'belvedere,panorama,Valle Osento,fotografia,natura,tramonto,centro storico',
    ],

    [
        'id'         => 'piazzetta-nicola-vella',
        'borough_id' => 'lacedonia',
        'category'   => 'Spazi Urbani',
        'sort_order' => 4,
        'name_it'    => 'Piazzetta Nicola Vella',
        'name_en'    => 'Piazzetta Nicola Vella',
        'desc_it'    => 'Nel cuore storico di Lacedonia si trova la suggestiva Piazzetta Nicola Vella, un piccolo gioiello urbano che racchiude un importante pezzo di storia civica. La piazzetta prende il nome da Nicola Vella, eletto sindaco di Lacedonia nelle prime elezioni amministrative dell\'Italia repubblicana con ampio consenso popolare nella lista del Fronte Popolare. Il suo mandato (1946–1951) fu un periodo di intensa attività politica e culturale: Vella promosse la costituzione del Consorzio Idrico dell\'Alta Irpinia nel 1946, combatté contro l\'arretratezza delle infrastrutture e l\'analfabetismo, e sostenne il movimento contadino per l\'occupazione delle terre incolte. Il suo impegno contribuì a formare una coscienza civica nuova in una comunità che, nel referendum istituzionale del 1946, votò per la Repubblica con il 60,3% dei consensi — un dato nettamente in controtendenza rispetto alla media provinciale e meridionale. La piazzetta, con i suoi edifici in pietra e la pavimentazione tradizionale, è oggi un luogo di memoria e identità collettiva. Il progetto MetaBorghi ha creato un modello 3D della piazzetta e degli edifici circostanti, che i visitatori possono esplorare virtualmente accedendo a contenuti sulla storia civica di Lacedonia nel dopoguerra.',
        'desc_en'    => 'In the historic heart of Lacedonia lies the evocative Piazzetta Nicola Vella, a small urban gem that holds an important piece of civic history. The square is named after Nicola Vella, elected mayor of Lacedonia in the first administrative elections of the Italian Republic with broad popular support. His term in office (1946–1951) was a period of intense political and cultural activity: Vella promoted the establishment of the Alta Irpinia Water Consortium in 1946, fought against infrastructural backwardness and illiteracy, and supported the peasant movement for the occupation of uncultivated land. His engagement helped shape a new civic consciousness in a community that, in the 1946 institutional referendum, voted for the Republic with 60.3% of the vote — a result clearly at odds with the provincial and southern Italian average. The square, with its stone buildings and traditional paving, is today a place of collective memory and identity. The MetaBorghi project has created a 3D model of the square and its surrounding buildings, which visitors can explore virtually while accessing content on Lacedonia\'s post-war civic history.',
        'tags'       => 'storia civica,Nicola Vella,dopoguerra,Repubblica,democrazia,centro storico,memoria collettiva',
    ],

    [
        'id'         => 'le-strette',
        'borough_id' => 'lacedonia',
        'category'   => 'Centro Storico',
        'sort_order' => 5,
        'name_it'    => 'Le Strette — Vicoli del Centro Storico',
        'name_en'    => 'Le Strette — Historic Alleyways',
        'desc_it'    => 'Il centro storico di Lacedonia è un affascinante intreccio di strade strette e vicoli che conservano intatta la stratificazione medievale del borgo. Queste stradine labirintiche — conosciute localmente come "Le Strette" — si snodano tra case in pietra calcarea costruite secondo le tecniche edilizie tipiche dell\'architettura irpina, con archi di raccordo, scalinate irregolari e portali in pietra lavorata che raccontano secoli di vita quotidiana. Il tessuto urbano rispecchia la morfologia del nucleo normanno-svevo originario, con la sua logica difensiva di vicoli stretti che rallentavano l\'avanzata dei nemici e garantivano la protezione degli abitanti. Ogni angolo nasconde una scoperta: un affresco votivo sbiadito, una meridiana incisa sul muro, un arco che affaccia su un cortile segreto. Passeggiare lentamente tra Le Strette è l\'esperienza più autentica che Lacedonia possa offrire al visitatore curioso. Il progetto MetaBorghi ha realizzato scansioni 3D per oltre 150.000 mq coprendo l\'intero centro storico, rendendo tutto il cuore del paese percorribile digitalmente in ogni suo dettaglio.',
        'desc_en'    => 'The historic centre of Lacedonia is a fascinating labyrinth of narrow streets and alleyways that preserve the medieval stratification of the village intact. These winding lanes — known locally as "Le Strette" — wind between limestone houses built using traditional Irpinian construction techniques, with connecting arches, irregular staircases and carved stone doorways that tell centuries of daily life. The urban fabric reflects the morphology of the original Norman-Swabian nucleus, with its defensive logic of narrow alleys designed to slow enemy advances and protect the inhabitants. Every corner holds a discovery: a faded votive fresco, a sundial carved into a wall, an arch opening onto a secret courtyard. Strolling slowly through Le Strette is the most authentic experience Lacedonia can offer the curious visitor. The MetaBorghi project has completed 3D scans covering over 150,000 square metres of the entire historic centre, making every corner of the village digitally walkable in full detail.',
        'tags'       => 'vicoli,centro storico,architettura medievale,pietra calcarea,normanno,cammino lento,fotografia',
    ],

    [
        'id'         => 'largo-tribuni',
        'borough_id' => 'lacedonia',
        'category'   => 'Spazi Urbani',
        'sort_order' => 6,
        'name_it'    => 'Largo Tribuni',
        'name_en'    => 'Largo Tribuni',
        'desc_it'    => 'Largo Tribuni è una delle piazze più vissute di Lacedonia, nota storicamente come sede del mercato settimanale del lunedì. Questa tradizione secolare continua ancora oggi: ogni lunedì mattina la piazza si anima di bancarelle, voci e incontri, riportando in scena un rito di scambio e socialità che affonda le radici nella storia agraria dell\'Irpinia. Il mercato di Largo Tribuni è stato per generazioni il luogo dove i contadini delle contrade vendevano i prodotti della terra, gli artigiani esponevano i propri manufatti e i paesani si ritrovavano per scambiare notizie. Negli ultimi anni, la piazza ha saputo reinventarsi: è diventata centro della vita notturna lacedoniese, sede di concerti estivi, spettacoli e manifestazioni culturali, adattandosi con vitalità alle esigenze contemporanee della comunità. Questa doppia anima — mercato tradizionale e spazio culturale moderno — rende Largo Tribuni uno dei luoghi più rappresentativi dell\'identità in trasformazione di Lacedonia. Il tour virtuale 3D realizzato dal progetto MetaBorghi documenta questo spazio nella sua dimensione storica e attuale.',
        'desc_en'    => 'Largo Tribuni is one of Lacedonia\'s most lively squares, historically known as the site of the weekly Monday market. This centuries-old tradition continues to this day: every Monday morning the square fills with market stalls, voices and encounters, re-enacting a ritual of exchange and sociability deeply rooted in the agrarian history of Irpinia. The Largo Tribuni market was, for generations, the place where farmers from outlying districts sold their produce, craftsmen displayed their wares and villagers gathered to share news. In recent years, the square has successfully reinvented itself: it has become the hub of Lacedonia\'s nightlife, hosting summer concerts, shows and cultural events, adapting with energy to the contemporary needs of the community. This dual identity — traditional market and modern cultural space — makes Largo Tribuni one of the most representative places of Lacedonia\'s evolving identity. The 3D virtual tour produced by the MetaBorghi project documents this space in both its historical and contemporary dimensions.',
        'tags'       => 'mercato,lunedì,vita sociale,eventi,cultura,centro storico,tradizione',
    ],

    /* ─── EDIFICI ───────────────────────────────────────────────────── */

    [
        'id'         => 'castello-pappacoda',
        'borough_id' => 'lacedonia',
        'category'   => 'Architettura',
        'sort_order' => 7,
        'name_it'    => 'Castello Pappacoda',
        'name_en'    => 'Castello Pappacoda',
        'desc_it'    => 'Il Castello Pappacoda domina maestoso il cuore di Lacedonia come uno dei più significativi esempi di architettura fortificata rinascimentale dell\'Irpinia. Commissionato da Ferdinando Pappacoda, feudatario di Lacedonia, e costruito tra il 1500 e il 1501, il castello integrava funzioni di residenza nobiliare e fortezza difensiva in un unico impianto strategico. Conosciuto anche come "Castello Nuovo" per distinguerlo da preesistenti strutture difensive, è caratterizzato da torri angolari, fossati, feritoie e passaggi sotterranei tipici dell\'architettura militare del tardo Quattrocento. I materiali costruttivi principali — pietra calcarea locale e tufo — riflettono le disponibilità del territorio e le scelte estetiche del periodo. Nonostante i danni causati dai terremoti del 1930 e del 1980, il castello conserva molte delle sue caratteristiche originali, ed è oggi di proprietà privata. Per valorizzare questo patrimonio nel rispetto della sua natura privata, il progetto MetaBorghi ha sviluppato un tour virtuale focalizzato sul perimetro esterno, arricchito da narrazioni interattive multilingua che approfondiscono la storia del castello, la sua importanza strategica e il suo ruolo nell\'architettura militare rinascimentale meridionale.',
        'desc_en'    => 'Castello Pappacoda stands majestically over the heart of Lacedonia as one of the most significant examples of Renaissance fortified architecture in Irpinia. Commissioned by Ferdinando Pappacoda, feudal lord of Lacedonia, and built between 1500 and 1501, the castle combined the functions of a noble residence and defensive fortress in a single strategic complex. Known as "Castello Nuovo" to distinguish it from earlier defensive structures, it features corner towers, moats, arrow slits and underground passages typical of late 15th-century military architecture. The main building materials — local limestone and tuff — reflect both the resources of the territory and the aesthetic choices of the period. Despite damage caused by the earthquakes of 1930 and 1980, the castle retains many of its original features and is today privately owned. To highlight this heritage while respecting its private nature, the MetaBorghi project has developed a virtual tour focused on the castle\'s external perimeter, enriched with multilingual interactive narratives exploring its history, strategic importance and role in Southern Italian Renaissance military architecture.',
        'tags'       => 'castello,Rinascimento,Pappacoda,architettura militare,feudalesimo,XVI secolo,Irpinia',
    ],

    [
        'id'         => 'casa-del-diavolo',
        'borough_id' => 'lacedonia',
        'category'   => 'Leggende e Folklore',
        'sort_order' => 8,
        'name_it'    => 'Casa del Diavolo',
        'name_en'    => 'Casa del Diavolo',
        'desc_it'    => 'Nel cuore di Lacedonia si erge la Casa del Diavolo, un\'enigmatica struttura arroccata su una rupe tufacea che sfida ogni logica costruttiva. Secondo la leggenda tramandata di generazione in generazione, questo edificio senza fondamenta sarebbe stato costruito in una sola notte dal diavolo stesso, in seguito a un patto con un abitante del luogo che aveva ceduto la sua anima in cambio di ricchezza o potere. La sua resistenza ai terremoti che hanno ripetutamente colpito la zona e la sua integrazione armoniosa con la conformazione geologica della rupe hanno alimentato per secoli il mistero e il fascino di questa costruzione unica. Dal punto di vista architettonico, l\'edificio rappresenta un caso di edilizia vernacolare di straordinario interesse: la capacità di adattare la struttura alle caratteristiche naturali del substrato geologico, sfruttando la rupe come fondazione naturale, testimonia una sapienza costruttiva antica e profonda. La Casa del Diavolo è oggi uno dei luoghi più fotografati e raccontati di Lacedonia, punto di incontro tra storia materiale e patrimonio immateriale orale. Il tour virtuale 3D del progetto MetaBorghi offre una visione a 360° dell\'edificio e dei suoi dintorni, arricchita da effetti sonori evocativi che ricreano l\'atmosfera misteriosa del luogo.',
        'desc_en'    => 'In the heart of Lacedonia stands the Casa del Diavolo (Devil\'s House), an enigmatic structure perched on a tuff rock outcrop that defies all constructive logic. According to legend passed down through generations, this building without foundations was constructed in a single night by the devil himself, following a pact with a local inhabitant who had surrendered his soul in exchange for wealth or power. Its resistance to the earthquakes that have repeatedly struck the area, and its harmonious integration with the geological conformation of the rock, have fuelled centuries of mystery and fascination around this unique structure. From an architectural perspective, the building represents an extraordinary case of vernacular construction: the capacity to adapt the structure to the natural characteristics of the geological substrate, using the rock as a natural foundation, testifies to deep and ancient constructive wisdom. The Casa del Diavolo is today one of Lacedonia\'s most photographed and storied landmarks, a meeting point between material history and intangible oral heritage. The MetaBorghi 3D virtual tour offers a 360° view of the building and its surroundings, enriched with evocative sound effects that recreate the mysterious atmosphere of the place.',
        'tags'       => 'leggenda,folklore,tufo,architettura vernacolare,patrimonio immateriale,mistero,fotografia',
    ],

    [
        'id'         => 'istituto-magistrale-de-sanctis',
        'borough_id' => 'lacedonia',
        'category'   => 'Istruzione e Cultura',
        'sort_order' => 9,
        'name_it'    => 'Istituto Magistrale Francesco De Sanctis',
        'name_en'    => 'Istituto Magistrale Francesco De Sanctis',
        'desc_it'    => 'L\'Istituto Magistrale di Lacedonia rappresenta uno dei lasciti più tangibili di Francesco De Sanctis alla sua terra. Fondato nel 1878 — l\'anno successivo alla nomina di De Sanctis a Ministro della Pubblica Istruzione nel governo Cairoli — fu inaugurato come Scuola Normale con l\'obiettivo di formare nuovi maestri elementari capaci di combattere l\'analfabetismo diffuso nel Mezzogiorno post-unitario. Lacedonia, borgo dell\'entroterra irpino, divenne così un polo culturale inatteso per l\'intera regione: De Sanctis volle offrire alla sua terra d\'origine uno strumento concreto di emancipazione attraverso l\'istruzione. Con l\'avvento della Riforma Gentile, la Scuola Normale si trasformò in Istituto Magistrale, attirando studenti da diverse regioni del Sud Italia. Gli anni Sessanta del Novecento segnarono il periodo di massima espansione dell\'istituto, con iscrizioni provenienti dall\'intera Campania e dalle regioni limitrofe. L\'edificio, ancora oggi presente nel centro storico, conserva negli spazi e nell\'architettura la memoria di questo straordinario capitolo della storia dell\'istruzione italiana. Il tour virtuale 3D realizzato da MetaBorghi permette di esplorare gli ambienti della scuola e i luoghi legati a De Sanctis, continuando idealmente l\'opera di diffusione del sapere iniziata quasi 150 anni fa.',
        'desc_en'    => 'The Istituto Magistrale of Lacedonia represents one of Francesco De Sanctis\'s most tangible legacies to his homeland. Founded in 1878 — the year following De Sanctis\'s appointment as Minister of Public Education in the Cairoli government — it was inaugurated as a Scuola Normale with the aim of training new primary school teachers capable of combating widespread illiteracy in post-unification Southern Italy. Lacedonia, a village in the Irpinian hinterland, thus became an unexpected cultural hub for the entire region: De Sanctis wished to offer his native land a concrete instrument of emancipation through education. With the advent of the Gentile Reform, the Scuola Normale was transformed into an Istituto Magistrale, attracting students from various regions of Southern Italy. The 1960s marked the institution\'s period of greatest expansion, with enrolments coming from the whole of Campania and neighbouring regions. The building, still standing in the historic centre today, preserves in its spaces and architecture the memory of this extraordinary chapter in the history of Italian education. The MetaBorghi 3D virtual tour allows visitors to explore the school\'s interiors and the places connected to De Sanctis, ideally continuing the work of spreading knowledge begun almost 150 years ago.',
        'tags'       => 'Francesco De Sanctis,istruzione,scuola,Ottocento,cultura,Risorgimento,storia dell\'educazione',
    ],

    [
        'id'         => 'casone-montevaccaro',
        'borough_id' => 'lacedonia',
        'category'   => 'Architettura Rurale',
        'sort_order' => 10,
        'name_it'    => 'Casone di Montevaccaro',
        'name_en'    => 'Casone di Montevaccaro',
        'desc_it'    => 'Immerso nella campagna lacedoniese, in contrada Montevaccaro, si erge il Casone di Montevaccaro, un\'antica masseria fortificata del XIX secolo che incarna la storia e le tradizioni dell\'Irpinia rurale. L\'imponente struttura quadrangolare in pietra locale, con le sue quattro torrette angolari, fu concepita con una duplice funzione: centro produttivo della lavorazione del latte e presidio difensivo contro il brigantaggio postunitario che imperversava nell\'entroterra meridionale. Il piano terra ospitava il grande vano con l\'imponente camino dedicato alla caseificazione; il primo piano era adibito ad abitazione; il sottotetto fungeva da colombaia. Le torrette angolari — di cui una conserva ancora una caratteristica scala a chiocciola — testimoniano l\'originaria vocazione difensiva dell\'edificio. Il Casone di Montevaccaro è situato nei pressi della Valle del Calaggio, area che nei secoli ha visto svolgersi eventi storici di grande importanza, dalle guerre sannitiche alle vicende del brigantaggio. Oggi rappresenta una delle testimonianze più complete dell\'architettura rurale irpina dell\'Ottocento, preziosa per comprendere l\'organizzazione del lavoro agricolo e caseario di un\'epoca in cui l\'Irpinia era ancora un mondo contadino vivo e pulsante. Il tour virtuale MetaBorghi offre una visione completa dell\'edificio e del paesaggio circostante.',
        'desc_en'    => 'Immersed in the Lacedonian countryside, in the district of Montevaccaro, stands the Casone di Montevaccaro, an ancient 19th-century fortified farmhouse that embodies the history and traditions of rural Irpinia. The imposing square stone structure, with its four corner turrets, was designed with a dual function: a productive centre for dairy processing and a defensive stronghold against the post-unification brigandage that plagued the Southern hinterland. The ground floor housed the large room with its imposing fireplace used for cheese-making; the first floor served as living quarters; the attic functioned as a dovecote. The corner turrets — one of which still retains a characteristic spiral staircase — testify to the building\'s original defensive purpose. The Casone di Montevaccaro is situated near the Valle del Calaggio, an area that has witnessed historically significant events over the centuries, from the Samnite wars to episodes of post-unification brigandage. Today it represents one of the most complete examples of 19th-century Irpinian rural architecture, invaluable for understanding the organisation of agricultural and dairy work in an era when Irpinia was still a vibrant peasant world. The MetaBorghi virtual tour offers a comprehensive view of the building and the surrounding landscape.',
        'tags'       => 'masseria,architettura rurale,XIX secolo,brigantaggio,caseificio,Valle del Calaggio,Irpinia contadina',
    ],

    [
        'id'         => 'palazzo-vescovile',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Ecclesiastico',
        'sort_order' => 11,
        'name_it'    => 'Palazzo Vescovile (Episcopio)',
        'name_en'    => 'Bishop\'s Palace (Episcopio)',
        'desc_it'    => 'L\'Episcopio di Lacedonia è un simbolo tangibile della resilienza storica e dell\'importanza ecclesiastica di questa città irpina. Secondo la tradizione narrata dal canonico Pasquale Palmese, il primo episcopio sorgeva nei pressi della Chiesa di San Nicola, prima di essere gravemente danneggiato dal devastante terremoto del 5 dicembre 1456. Quella catastrofe spinse a ripensare l\'intero assetto urbano del borgo: il vescovo Giacomo de Cavaline (1452–1463) avviò i primi lavori di ripristino, ma fu nel corso del XV secolo che l\'episcopio fu trasferito nell\'attuale ubicazione. Gli interventi di restauro si succedettero nei secoli: il vescovo Antonio De Dura (1506–1538) ne consolidò la nuova sede nel primo Cinquecento; il terremoto del 1694 richiese nuovi lavori, voluti dal vescovo Giovan Battista La Morea (1684–1711). Oggi il Palazzo Vescovile ospita il Museo Diocesano San Gerardo Maiella, che custodisce un patrimonio artistico di straordinario valore: una spada italica del IV secolo a.C., il celebre Trittico di Andrea Sabatini da Salerno (fine Quattrocento), oltre cento pergamene medievali e la completa edizione francese dell\'Encyclopédie di Diderot del XVIII secolo. Il tour virtuale MetaBorghi consente di esplorare l\'edificio e le sue collezioni in modo immersivo.',
        'desc_en'    => 'The Episcopio of Lacedonia is a tangible symbol of the historical resilience and ecclesiastical importance of this Irpinian town. According to tradition recounted by canon Pasquale Palmese, the first bishop\'s palace stood near the Church of San Nicola before being severely damaged by the devastating earthquake of 5 December 1456. That catastrophe prompted a complete rethinking of the town\'s urban layout: Bishop Giacomo de Cavaline (1452–1463) began initial restoration works, and it was during the 15th century that the episcopio was relocated to its present site. Restoration works continued through the centuries: Bishop Antonio De Dura (1506–1538) consolidated the new seat in the early 16th century, while the earthquake of 1694 required further works commissioned by Bishop Giovan Battista La Morea (1684–1711). Today the Bishop\'s Palace houses the Diocesan Museum of San Gerardo Maiella, which preserves an extraordinarily valuable artistic heritage: an Italic sword from the 4th century BC, the celebrated Triptych of Andrea Sabatini da Salerno (late 15th century), over one hundred medieval parchments and the complete French edition of Diderot\'s Encyclopédie from the 18th century. The MetaBorghi virtual tour allows visitors to explore the building and its collections in an immersive way.',
        'tags'       => 'episcopio,vescovo,museo diocesano,arte sacra,terremoto 1456,San Gerardo Maiella,storia ecclesiastica',
    ],

    [
        'id'         => 'teatro-comunale',
        'borough_id' => 'lacedonia',
        'category'   => 'Arte e Cultura',
        'sort_order' => 12,
        'name_it'    => 'Teatro Comunale',
        'name_en'    => 'Municipal Theatre',
        'desc_it'    => 'Il Teatro Comunale di Lacedonia è un gioiello culturale che si è affermato come punto di riferimento per l\'intera Irpinia orientale. Dopo importanti interventi di ammodernamento strutturale e tecnico, il teatro è oggi una struttura all\'avanguardia capace di ospitare produzioni di alto livello in un contesto di eccezionale calore umano. Ciò che distingue il Teatro Comunale di Lacedonia è la qualità e la varietà del suo cartellone: la programmazione spazia dal teatro classico alle produzioni contemporanee, dalla musica alla danza, offrendo alla comunità locale e ai visitatori una finestra privilegiata sulla cultura italiana e internazionale. In un borgo dell\'Appennino meridionale, la presenza di un teatro attivo con programmazione regolare è un fatto non scontato, che testimonia la vitalità culturale di Lacedonia e la volontà della sua comunità di investire nella qualità della vita e nell\'attrattività del territorio. Il teatro rappresenta anche uno strumento di coesione sociale: gli spettacoli diventano occasione di incontro, dibattito e condivisione per una comunità che sa tenere insieme tradizione e innovazione. Il progetto MetaBorghi ha mappato l\'intera struttura in un modello digitale navigabile, con informazioni sul cartellone e la possibilità futura di prenotare biglietti direttamente attraverso la piattaforma.',
        'desc_en'    => 'The Municipal Theatre of Lacedonia is a cultural gem that has established itself as a point of reference for the entire eastern Irpinia region. Following significant structural and technical modernisation works, the theatre is today a state-of-the-art venue capable of hosting high-quality productions in a setting of exceptional human warmth. What sets the Theatre apart is the quality and variety of its programme: performances range from classical theatre to contemporary productions, from music to dance, offering the local community and visitors a privileged window onto Italian and international culture. In a village of the Southern Apennines, the presence of an active theatre with a regular programme is far from a given, and testifies to the cultural vitality of Lacedonia and its community\'s determination to invest in quality of life and territorial attractiveness. The theatre also serves as an instrument of social cohesion: performances become occasions for encounter, debate and sharing in a community that knows how to hold together tradition and innovation. The MetaBorghi project has mapped the entire building into a navigable digital model, with information on current and past programmes and the future possibility of booking tickets directly through the platform.',
        'tags'       => 'teatro,cultura,musica,danza,spettacolo,vita culturale,programmazione,Irpinia',
    ],

    /* ─── MONUMENTI ────────────────────────────────────────────────── */

    [
        'id'         => 'porta-di-sopra',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Storico',
        'sort_order' => 13,
        'name_it'    => 'Porte d\'Ingresso della Cittadella Medievale',
        'name_en'    => 'Gates of the Medieval Citadel',
        'desc_it'    => 'Nel centro storico di Lacedonia si ergono ancora visibili le vestigia delle mura di cinta della Cittadella Medievale, importante testimonianza dell\'architettura difensiva feudale. Costruite dai feudatari Orsini, Principi di Taranto, dopo il devastante terremoto del 5 dicembre 1456, queste mura proteggevano la città posizionata nella zona sud-est della collina. La cittadella era accessibile attraverso quattro porte principali: la Porta del Messere (o di Sopra), la Porta la Stella, la Porta degli Albanesi e la Porta di Sotto (o di Basso). Ciascuna porta era dedicata a un santo patrono, e un profondo fossato — il cui ricordo sopravvive ancora nel toponimo dialettale "Lù Fuoss" — le collegava in un sistema difensivo integrato. Questi varchi non erano semplici aperture nelle mura: erano monumenti in pietra calcarea con archi a tutto sesto o a sesto acuto, decorati con stemmi araldici e immagini sacre. Sopravvissute ai terremoti del 1930 e del 1980, le porte rimangono tra i resti più eloquenti della Lacedonia medievale. Utilizzando tecnologie di scansione laser e fotogrammetria, il progetto MetaBorghi ha creato un modello 3D dettagliato delle porte d\'ingresso, rendendone accessibile la storia a un pubblico globale.',
        'desc_en'    => 'In the historic centre of Lacedonia, the remains of the walls of the Medieval Citadel are still visible — an important testimony to feudal defensive architecture. Built by the Orsini feudal lords, Princes of Taranto, following the devastating earthquake of 5 December 1456, these walls protected the town situated on the south-eastern slope of the hill. The citadel was accessible through four main gates: the Porta del Messere (or "di Sopra" — Upper Gate), the Porta la Stella, the Porta degli Albanesi and the Porta di Sotto (or Lower Gate). Each gate was dedicated to a patron saint, and a deep moat — whose memory survives in the dialect toponym "Lù Fuoss" — connected them in an integrated defensive system. These passageways were not mere openings in the walls: they were limestone monuments with rounded or pointed arches, decorated with heraldic crests and sacred images. Having survived the earthquakes of 1930 and 1980, the gates remain among the most eloquent remains of medieval Lacedonia. Using laser scanning and photogrammetry technologies, the MetaBorghi project has created a detailed 3D model of the entrance gates, making their history accessible to a global audience.',
        'tags'       => 'mura medievali,porte d\'ingresso,Orsini,Cittadella medievale,1456,architettura difensiva,fossato',
    ],

    [
        'id'         => 'colonna-del-pedoca',
        'borough_id' => 'lacedonia',
        'category'   => 'Monumenti',
        'sort_order' => 14,
        'name_it'    => 'Colonna del Pedoca',
        'name_en'    => 'Colonna del Pedoca',
        'desc_it'    => 'Al centro di Lacedonia si erge la Colonna del Pedoca, un monumento storico che porta impressa la firma di un preciso momento della storia ecclesiastica locale. La colonna, sormontata da una croce, prende il nome dal vescovo Marco Pedoca, che la fece erigere nel 1587 come atto devozionale e segno visibile della presenza della Chiesa nel tessuto urbano del borgo. Marco Pedoca, originario di Mirandola (Modena) e proveniente da un\'illustre famiglia, fu ordinato vescovo da papa Gregorio XIII il 14 maggio 1584, portando con sé un\'esperienza ecclesiastica maturata come abate a Sant\'Angelo di Ravenna. La colonna ha una storia di mobilità all\'interno del tessuto urbano di Lacedonia: originariamente collocata nei pressi dell\'antica cattedrale di Santa Maria della Cancellata, è stata spostata due volte nel corso dei secoli per adattarsi all\'espansione e alle trasformazioni del centro abitato. Attualmente trova la sua collocazione di fronte alla chiesa sconsacrata di Santa Maria della Consolazione, nel cuore storico del borgo. Questo monumento in pietra calcarea è una testimonianza preziosa dell\'identità religiosa di Lacedonia e dell\'attenzione con cui la comunità ha saputo conservare e tramandare i propri simboli attraverso i secoli.',
        'desc_en'    => 'At the centre of Lacedonia stands the Colonna del Pedoca, a historic monument bearing the imprint of a precise moment in local ecclesiastical history. The column, surmounted by a cross, takes its name from Bishop Marco Pedoca, who had it erected in 1587 as a devotional act and visible sign of the Church\'s presence in the urban fabric of the village. Marco Pedoca, originally from Mirandola (Modena) and of illustrious family, was ordained bishop by Pope Gregory XIII on 14 May 1584, bringing with him ecclesiastical experience gained as abbot at Sant\'Angelo di Ravenna. The column has a history of movement within Lacedonia\'s urban fabric: originally located near the ancient cathedral of Santa Maria della Cancellata, it was relocated twice over the centuries to accommodate the expansion and transformation of the town centre. It now stands in front of the deconsecrated church of Santa Maria della Consolazione, in the historic heart of the village. This limestone monument is a precious testimony to Lacedonia\'s religious identity and to the care with which the community has preserved and passed down its symbols through the centuries.',
        'tags'       => 'colonna,croce,vescovo Pedoca,1587,arte religiosa,pietra calcarea,storia ecclesiastica',
    ],

    [
        'id'         => 'monumento-de-sanctis',
        'borough_id' => 'lacedonia',
        'category'   => 'Monumenti',
        'sort_order' => 15,
        'name_it'    => 'Monumento a Francesco De Sanctis',
        'name_en'    => 'Monument to Francesco De Sanctis',
        'desc_it'    => 'In Piazza Francesco De Sanctis si erge il monumento dedicato al pensatore irpino più illustre: Francesco De Sanctis (1817–1883), critico letterario, filosofo, politico e padre fondatore della moderna critica letteraria italiana. L\'opera bronzea — realizzata dallo scultore napoletano Vincenzo Jerace, uno dei maestri della scultura italiana di fine Ottocento — ritrae De Sanctis su un alto basamento in pietra calcarea in atteggiamento meditativo, la testa leggermente piegata in avanti, lo sguardo rivolto verso l\'orizzonte culturale che aveva dedicato la vita a esplorare. La statua è circondata da una serie di elementi toponomastici e culturali che formano un sistema commemorativo coerente: la piazza stessa, l\'Istituto Magistrale che porta il suo nome, la via a lui dedicata nel centro storico. De Sanctis rappresenta per Lacedonia molto più di un illustre concittadino: è il simbolo vivente del potere della cultura come strumento di emancipazione del Mezzogiorno, l\'incarnazione dell\'idea che la periferia geografica possa produrre pensiero universale. Il monumento è visitabile all\'interno del tour virtuale 3D di Piazza De Sanctis realizzato da MetaBorghi.',
        'desc_en'    => 'In Piazza Francesco De Sanctis stands the monument dedicated to Irpinia\'s most illustrious thinker: Francesco De Sanctis (1817–1883), literary critic, philosopher, politician and founding father of modern Italian literary criticism. The bronze work — created by Neapolitan sculptor Vincenzo Jerace, one of the masters of late 19th-century Italian sculpture — portrays De Sanctis on a tall limestone base in a meditative pose, his head slightly tilted forward, his gaze turned towards the cultural horizon to which he had devoted his life\'s work. The statue is surrounded by a series of topographic and cultural elements that form a coherent commemorative system: the square itself, the teacher training institute bearing his name, and the street dedicated to him in the historic centre. De Sanctis represents for Lacedonia far more than a distinguished townsman: he is the living symbol of the power of culture as an instrument of emancipation for the South of Italy, the embodiment of the idea that a geographical periphery can produce universal thought. The monument can be visited within the 3D virtual tour of Piazza De Sanctis created by MetaBorghi.',
        'tags'       => 'Francesco De Sanctis,statua,bronzo,Vincenzo Jerace,critica letteraria,Risorgimento,cultura,Mezzogiorno',
    ],

    [
        'id'         => 'monumento-caduti',
        'borough_id' => 'lacedonia',
        'category'   => 'Monumenti',
        'sort_order' => 16,
        'name_it'    => 'Monumento ai Caduti in Guerra',
        'name_en'    => 'War Memorial',
        'desc_it'    => 'Nel cuore di Lacedonia, nell\'omonima piazza adiacente alla Basilica di Santa Maria della Cancellata, si erge il Monumento ai Caduti in Guerra, un\'opera di profondo significato storico e simbolico. L\'opera è stata realizzata dall\'artista venosino Nicola Di Vietri e si distingue per la potente simbologia della sua figura centrale: un milite senza armi nell\'atto di deporre il proprio elmetto, gesto che incarna la rinuncia alla guerra e l\'aspirazione alla pace dopo la devastazione dei conflitti mondiali. Questo gesto — così semplice e così carico di significato — non è una celebrazione della guerra, ma una sua negazione: è il riconoscimento del sacrificio di chi è tornato e di chi non è tornato, e la speranza che simili sacrifici non si ripetano. Ai lati del monumento, due lapidi commemorative riportano i nomi dei lacedoniesi caduti e dispersi durante la Prima e la Seconda Guerra Mondiale, personalizzando il ricordo nazionale nelle storie individuali della comunità locale. Il monumento è parte integrante dell\'identità di Lacedonia: ogni anno, nelle ricorrenze del 4 novembre e del 25 aprile, la comunità si raccoglie qui in un rito civile di memoria e gratitudine. Il tour virtuale MetaBorghi consente di leggere da vicino le iscrizioni delle lapidi e di accedere a informazioni storiche sul contributo di Lacedonia ai conflitti del XX secolo.',
        'desc_en'    => 'In the heart of Lacedonia, in the square of the same name adjacent to the Basilica of Santa Maria della Cancellata, stands the War Memorial, a work of deep historical and symbolic significance. The piece was created by the Venosa-born artist Nicola Di Vietri and is distinguished by the powerful symbolism of its central figure: an unarmed soldier in the act of laying down his helmet — a gesture that embodies the renunciation of war and the aspiration for peace after the devastation of the world conflicts. This gesture — so simple and yet so charged with meaning — is not a celebration of war, but a denial of it: it is the acknowledgment of the sacrifice of those who returned and those who did not, and the hope that such sacrifices will not be repeated. On either side of the monument, two commemorative plaques bear the names of Lacedonian soldiers killed and missing during the First and Second World Wars, personalising the national memory in the individual stories of the local community. The MetaBorghi virtual tour allows visitors to closely read the inscriptions on the plaques and access historical information on Lacedonia\'s contribution to the conflicts of the 20th century.',
        'tags'       => 'guerra,caduti,Prima Guerra Mondiale,Seconda Guerra Mondiale,memoria,lapide,Nicola Di Vietri,pace',
    ],

    [
        'id'         => 'lapide-terremoto-1930',
        'borough_id' => 'lacedonia',
        'category'   => 'Monumenti',
        'sort_order' => 17,
        'name_it'    => 'Lapide del Terremoto del 1930',
        'name_en'    => 'Earthquake Memorial Plaque (1930)',
        'desc_it'    => 'Una lapide in pietra calcarea custodisce la memoria del devastante terremoto del 23 luglio 1930, uno degli eventi più traumatici della storia moderna di Lacedonia. Collocata in posizione centrale e ben visibile nel tessuto urbano del borgo, questa testimonianza in pietra non si limita a ricordare le vittime della tragedia: è anche un monito sull\'importanza della prevenzione sismica e della costruzione sicura in un territorio ad alto rischio come quello dell\'Appennino campano-lucano. Il terremoto del 1930 causò gravissimi danni al patrimonio edilizio e ai monumenti storici di Lacedonia, costringendo alla ricostruzione o al restauro di numerosi edifici storici, tra cui diverse chiese. La risposta della comunità fu quella di ricostruire, non di abbandonare: testimonianza di una resilienza profonda che si ripeterà cinquant\'anni dopo, con il devastante sisma del 23 novembre 1980. L\'area circostante la lapide è stata curata come spazio di riflessione e memoria: un luogo dove fermarsi, leggere le incisioni in pietra e meditare sulla capacità di una comunità di rinascere dopo l\'avversità. Il tour virtuale 3D di MetaBorghi include una galleria digitale di Lacedonia prima e dopo il terremoto del 1930.',
        'desc_en'    => 'A limestone plaque preserves the memory of the devastating earthquake of 23 July 1930, one of the most traumatic events in the modern history of Lacedonia. Placed in a central and clearly visible position within the village\'s urban fabric, this stone testimony does not merely remember the victims of the tragedy: it also serves as a reminder of the importance of seismic prevention and safe construction in a high-risk territory such as the Campano-Lucanian Apennines. The 1930 earthquake caused severe damage to Lacedonia\'s building heritage and historic monuments, forcing the reconstruction or restoration of numerous historic buildings, including several churches. The community\'s response was to rebuild, not to abandon — a testament to a deep resilience that would be demonstrated once more fifty years later, following the devastating earthquake of 23 November 1980. The area surrounding the plaque has been maintained as a space for reflection and memory: a place to pause, read the stone inscriptions and meditate on a community\'s capacity to be reborn after adversity. The MetaBorghi 3D virtual tour includes a digital gallery of Lacedonia before and after the 1930 earthquake.',
        'tags'       => 'terremoto 1930,lapide,memoria,resilienza,prevenzione sismica,ricostruzione,storia contemporanea',
    ],

    /* ─── MUSEI ─────────────────────────────────────────────────────── */

    [
        'id'         => 'mavi',
        'borough_id' => 'lacedonia',
        'category'   => 'Musei',
        'sort_order' => 18,
        'name_it'    => 'MAVI — Museo Antropologico Visivo Irpino',
        'name_en'    => 'MAVI — Irpinian Visual Anthropology Museum',
        'desc_it'    => 'Il MAVI (Museo Antropologico Visivo Irpino) di Lacedonia è una finestra straordinaria sul mondo contadino dell\'Irpinia degli anni Cinquanta. Ospitato in un elegante edificio ottocentesco nel cuore del borgo, il museo nasce dalla riscoperta di 1.801 fotografie scattate nel 1957 dall\'antropologo statunitense Frank Cancian, che trascorse un intero anno immerso nella vita quotidiana della comunità lacedoniese. Le fotografie — in bianco e nero, di straordinaria qualità documentaria — ritraggono ogni aspetto di una civiltà contadina allora ancora viva ma già in rapida trasformazione: i gesti del lavoro nei campi, le feste religiose, i riti del ciclo della vita, il mondo delle donne, i bambini che giocano per strada, i vecchi seduti davanti alle porte. Entrando al MAVI, i visitatori intraprendono un viaggio nel tempo verso un\'Irpinia che non esiste più ma che ha plasmato in modo indelebile l\'identità culturale di queste comunità. Le fotografie sono raggruppate per temi, consentendo un\'esplorazione sistematica degli aspetti della vita contadina. Il MAVI attira studiosi, appassionati di antropologia visiva e turisti culturali da tutta Italia e dall\'estero. Il modello digitale 3D realizzato da MetaBorghi permette di esplorare gli spazi del museo e le sue collezioni anche a distanza.',
        'desc_en'    => 'The MAVI (Irpinian Visual Anthropology Museum) in Lacedonia is an extraordinary window onto the peasant world of Irpinia in the 1950s. Housed in an elegant 19th-century building in the heart of the village, the museum was born from the rediscovery of 1,801 photographs taken in 1957 by American anthropologist Frank Cancian, who spent an entire year immersed in the daily life of the Lacedonian community. The photographs — in black and white, of extraordinary documentary quality — capture every aspect of a peasant civilization that was still alive but already undergoing rapid transformation: the gestures of field work, religious festivals, the rituals of the life cycle, the world of women, children playing in the streets, elders seated in front of their doorways. Entering the MAVI, visitors embark on a journey back in time to an Irpinia that no longer exists but that has indelibly shaped the cultural identity of these communities. The photographs are grouped by theme, allowing systematic exploration of aspects of peasant life. The MAVI attracts scholars, visual anthropology enthusiasts and cultural tourists from across Italy and abroad. The 3D digital model created by MetaBorghi allows the museum\'s spaces and collections to be explored remotely.',
        'tags'       => 'MAVI,Frank Cancian,antropologia visiva,fotografia,anni Cinquanta,civiltà contadina,museo,Irpinia,memoria',
    ],

    [
        'id'         => 'museo-diocesano',
        'borough_id' => 'lacedonia',
        'category'   => 'Musei',
        'sort_order' => 19,
        'name_it'    => 'Museo Diocesano San Gerardo Maiella',
        'name_en'    => 'Diocesan Museum of San Gerardo Maiella',
        'desc_it'    => 'L\'ex Episcopio di Lacedonia, un tempo dimora dei vescovi, è oggi trasformato nel Museo Diocesano dedicato a San Gerardo Maiella, il santo che visse in questo luogo per oltre tre anni al servizio del vescovo Albini. Il museo custodisce un patrimonio di eccezionale valore storico e artistico. Al piano terra si trova il Pozzo del Miracolo, scenario di uno degli episodi più noti attribuiti al santo: secondo la tradizione, Gerardo vi immerse la statua di Gesù Bambino per recuperare miracolosamente la chiave della stanza del vescovo. Il patrimonio archeologico esposto comprende reperti di straordinaria importanza: una spada italica del IV secolo a.C., cippi funerari e onorari, epigrafi con la dicitura "Municipium Aquiloniae", ceramiche e argenti di epoche sannita, romana e medievale. Tra i tesori artistici spicca il celebre Trittico di Andrea Sabatini da Salerno (fine Quattrocento), legato secondo la tradizione a un ringraziamento del re Ferrante d\'Aragona per essere scampato alla Congiura dei Baroni (1485–1487). La biblioteca conserva oltre cento pergamene medievali e l\'edizione completa in lingua francese dell\'Encyclopédie di Diderot del XVIII secolo. Il tutto visitabile anche attraverso il tour virtuale MetaBorghi.',
        'desc_en'    => 'The former Episcopio of Lacedonia, once the residence of its bishops, has been transformed into the Diocesan Museum dedicated to San Gerardo Maiella, the saint who lived in this very place for over three years in the service of Bishop Albini. The museum preserves a heritage of exceptional historical and artistic value. On the ground floor stands the Pozzo del Miracolo (Well of the Miracle), the setting of one of the most celebrated episodes attributed to the saint: according to tradition, Gerardo immersed a statue of the Christ Child in the well to miraculously recover the key to the bishop\'s room. The archaeological heritage on display includes finds of extraordinary importance: an Italic sword from the 4th century BC, funerary and honorary cippi, inscriptions bearing the text "Municipium Aquiloniae", as well as ceramics and silverware from Samnite, Roman and medieval periods. Among the artistic treasures stands the celebrated Triptych of Andrea Sabatini da Salerno (late 15th century), linked by tradition to a thanksgiving offering from King Ferrante of Aragon for having survived the Barons\' Conspiracy (1485–1487). The library preserves over one hundred medieval parchments and the complete French edition of Diderot\'s Encyclopédie from the 18th century. All of this can also be explored through the MetaBorghi virtual tour.',
        'tags'       => 'museo diocesano,San Gerardo Maiella,arte sacra,archeologia,spada italica,Trittico Sabatini,Ferrante d\'Aragona,pergamene,Diderot',
    ],

    /* ─── CHIESE ─────────────────────────────────────────────────────── */

    [
        'id'         => 'santa-maria-cancellata',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Religioso',
        'sort_order' => 20,
        'name_it'    => 'Basilica di Santa Maria della Cancellata',
        'name_en'    => 'Basilica of Santa Maria della Cancellata',
        'desc_it'    => 'Santa Maria della Cancellata è una delle chiese più antiche e storicamente stratificate di Lacedonia. Edificata su un sito di culto di origine paleocristiana, sorge sulle vestigia di un santuario consacrato in età romana alla dea Iside: la continuità sacrale del luogo attraversa dunque oltre due millenni di storia. Nel II secolo d.C. il tempio pagano fu convertito in luogo di culto cristiano. Nel XVIII secolo, con la costruzione della nuova cattedrale nel centro del borgo, l\'antica chiesa cadde in abbandono, per essere poi ricostruita nel secolo successivo sull\'impianto dell\'antico tempio. Dopo il terremoto del 1930, la chiesa fu ristrutturata e affidata all\'Ordine Francescano. Il patrimonio spirituale della Cancellata è arricchito da un evento straordinario: nel 1948, l\'effigie della Madonna dell\'Addolorata custodita all\'interno della chiesa si animò e versò lacrime per circa dieci giorni, suscitando l\'attenzione dei media nazionali e attirando una marea di fedeli da tutto il Centro e il Meridione d\'Italia. La chiesa custodisce mosaici paleocristiani, iscrizioni latine e opere d\'arte sacra che i visitatori possono ammirare nei minimi dettagli grazie al tour virtuale 3D di MetaBorghi.',
        'desc_en'    => 'Santa Maria della Cancellata is one of Lacedonia\'s oldest and most historically layered churches. Built on a site of early Christian worship, it stands on the remains of a Roman-era sanctuary consecrated to the goddess Isis — making the sacred continuity of this place span over two millennia of history. In the 2nd century AD the pagan temple was converted into a Christian place of worship. In the 18th century, with the construction of the new cathedral in the centre of the village, the ancient church fell into abandonment, before being rebuilt in the following century on the foundations of the ancient temple. After the earthquake of 1930, the church was restructured and entrusted to the Franciscan Order. The spiritual heritage of La Cancellata is enriched by an extraordinary event: in 1948, the effigy of the Madonna dell\'Addolorata kept inside the church came to life and wept for approximately ten days, attracting national media attention and drawing thousands of faithful from across Central and Southern Italy. The church preserves early Christian mosaics, Latin inscriptions and sacred artworks that visitors can admire in the finest detail through the MetaBorghi 3D virtual tour.',
        'desc_en'    => 'Santa Maria della Cancellata is one of Lacedonia\'s oldest and most historically layered churches, standing on the remains of a Roman-era sanctuary dedicated to the goddess Isis. Its sacred continuity spans over two millennia. In the 2nd century AD the pagan temple became a Christian place of worship; rebuilt in the 19th century after a period of abandonment, it was restructured after the 1930 earthquake and entrusted to the Franciscans. The church holds a remarkable place in Lacedonia\'s spiritual life: in 1948, the effigy of the Madonna dell\'Addolorata kept inside wept for approximately ten days, drawing national press attention and thousands of faithful from across Italy. The church preserves early Christian mosaics, Latin inscriptions and sacred artworks that visitors can explore in detail through the MetaBorghi 3D virtual tour.',
        'tags'       => 'paleocristiano,Iside,Madonna Addolorata,lacrime,Francescani,arte sacra,mosaici,culto,storia religiosa',
    ],

    [
        'id'         => 'chiesa-san-filippo-neri',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Religioso',
        'sort_order' => 21,
        'name_it'    => 'Chiesa di San Filippo Neri',
        'name_en'    => 'Church of San Filippo Neri',
        'desc_it'    => 'Sulla Piazza intitolata a Francesco De Sanctis sorge la chiesa consacrata a San Filippo Neri, il "Santo dell\'Allegria", venerato da secoli come Compatrono di Lacedonia. La storia di questo culto risale al 1782, quando la devozione a San Filippo si radicò profondamente nella comunità lacedoniese. Ogni anno, il 26 maggio, la città si anima con una serie di manifestazioni che coinvolgono tutta la cittadinanza: la funzione solenne in chiesa, il corteo processionale per le vie del centro storico, e i festeggiamenti in Piazza Francesco De Sanctis e in Largo Tribuni. L\'edificio sacro, con la sua architettura barocca tardiva, custodisce altari riccamente decorati, affreschi e un apparato di arredi sacri di notevole interesse artistico. La chiesa è stata digitalizzata in un modello 3D esplorabile arricchito da effetti sonori che evocano l\'atmosfera delle celebrazioni: i fedeli in preghiera, le campane, la processione. Questo strumento digitale permette di comprendere non solo l\'architettura dell\'edificio ma anche il significato culturale e devozionale che esso riveste per la comunità, il legame indissolubile tra il santo, Lacedonia e i suoi abitanti attraverso quasi due secoli e mezzo di culto condiviso.',
        'desc_en'    => 'On Piazza Francesco De Sanctis stands the church dedicated to San Filippo Neri, the "Saint of Joy," venerated for centuries as Co-patron of Lacedonia. The history of this cult dates back to 1782, when devotion to San Filippo took deep root in the Lacedonian community. Every year on 26 May, the town comes alive with a series of events involving the entire citizenry: the solemn Mass, the procession through the streets of the historic centre, and celebrations in Piazza Francesco De Sanctis and Largo Tribuni. The sacred building, with its late Baroque architecture, houses richly decorated altars, frescoes and sacred furnishings of considerable artistic interest. The church has been digitized into an explorable 3D model enriched with ambient sounds evoking the atmosphere of its celebrations: the faithful in prayer, church bells, the procession. This digital tool allows visitors to understand not only the architecture of the building but also the cultural and devotional significance it holds for the community — the indissoluble bond between the saint, Lacedonia and its inhabitants across nearly two and a half centuries of shared devotion.',
        'tags'       => 'San Filippo Neri,barocco,patrono,festa,processione,devozione,XVII secolo,Piazza De Sanctis',
    ],

    [
        'id'         => 'santuario-madonna-grazie',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Religioso',
        'sort_order' => 22,
        'name_it'    => 'Santuario della Madonna delle Grazie',
        'name_en'    => 'Sanctuary of the Madonna delle Grazie',
        'desc_it'    => 'Situato in aperta campagna nella località "Forna", ai piedi di un\'altura vicino al torrente Osento, il Santuario della Madonna delle Grazie è uno dei luoghi più amati e frequentati di Lacedonia. Le origini precise del culto e dell\'edificio rimangono incerte, con ipotesi che lo datano al XVI secolo: la tradizione lega la sua fondazione ai mandriani montellesi che frequentavano la zona durante la transumanza e che, secondo la leggenda, ritrovarono una statua della Madonna in un arbusto. Nel 1850, la chiesa crollò durante lavori di restauro: fu ricostruita grazie alle offerte dei fedeli (120 ducati d\'oro) e al contributo del re Ferdinando II di Borbone (100 ducati d\'oro). La vita devozionale legata al santuario è scandita da un rito annuale di grande intensità spirituale: il Lunedì dell\'Angelo, la statua della Madonna viene portata in processione dalla campagna fino alla Cattedrale di Lacedonia, dove rimane per un mese, per tornare poi al santuario nella prima domenica di maggio. L\'area intorno al santuario è stata attrezzata per accogliere fedeli e visitatori con spazi per pic-nic all\'ombra di alberi secolari. Il tour virtuale MetaBorghi documenta sia la chiesa che l\'area naturalistica circostante.',
        'desc_en'    => 'Located in open countryside in the locality of "Forna," at the foot of a hill near the Osento stream, the Sanctuary of the Madonna delle Grazie is one of Lacedonia\'s most cherished and frequently visited places. The precise origins of the cult and building remain uncertain, with hypotheses dating it to the 16th century: tradition links its foundation to shepherds from Montella who frequented the area during transhumance and who, according to legend, discovered a statue of the Madonna in a bush. In 1850, the church collapsed during restoration works: it was rebuilt thanks to offerings from the faithful (120 gold ducats) and a contribution from King Ferdinand II of Bourbon (100 gold ducats). Devotional life linked to the sanctuary is marked by an annual rite of great spiritual intensity: on Easter Monday, the statue of the Madonna is carried in procession from the countryside to Lacedonia\'s cathedral, where she remains for a month before returning to the sanctuary on the first Sunday of May. The area around the sanctuary has been equipped to welcome the faithful and visitors, with picnic spaces in the shade of ancient trees. The MetaBorghi virtual tour documents both the church and the surrounding natural area.',
        'tags'       => 'Madonna delle Grazie,santuario,transumanza,processione,Lunedì dell\'Angelo,XVI secolo,devozione popolare,natura',
    ],

    [
        'id'         => 'chiesa-santa-maria-assunta',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Religioso',
        'sort_order' => 23,
        'name_it'    => 'Chiesa di Santa Maria Assunta (Cattedrale)',
        'name_en'    => 'Church of Santa Maria Assunta (Cathedral)',
        'desc_it'    => 'Familiarmente chiamata dai lacedoniesi "Chiesa Madre" o "Cattedrale", la Chiesa di Santa Maria Assunta si erge nel cuore del paese come il principale luogo di culto della comunità. Le sue origini risalgono al XVI secolo: nell\'area oggi occupata dal campanile sorgeva anticamente un modesto edificio di culto dedicato a Sant\'Antonio, tristemente noto per un episodio storico drammatico — nella notte tra il 10 e l\'11 settembre 1486, i nobili meridionali in rivolta contro il re Ferrante d\'Aragona vi giurarono di espellere gli aragonesi dal regno di Napoli. L\'attuale chiesa fu costruita nel XVI secolo e ampliata nei due secoli successivi: le navate passarono da una a tre, e fu innalzata l\'imponente torre campanaria che tuttora sovrasta il centro storico di Lacedonia. Questi interventi conferirono all\'edificio la grandiosità e la solennità tipiche dell\'architettura ecclesiastica barocca meridionale. L\'interno custodisce affreschi, opere d\'arte sacra e arredi di notevole pregio, severamente danneggiati dal terremoto del 1980 e successivamente restaurati. La chiesa è stata digitalizzata in un modello 3D navigabile che consente di ammirare da vicino i dettagli degli affreschi e degli arredi sacri.',
        'desc_en'    => 'Affectionately called by Lacedonian residents simply "Chiesa Madre" or "Cattedrale," the Church of Santa Maria Assunta stands at the heart of the town as the community\'s principal place of worship. Its origins date to the 16th century: where the bell tower now stands, there once stood a modest chapel dedicated to Sant\'Antonio — a place sadly marked by a dramatic historical episode. On the night of 10–11 September 1486, southern nobles in revolt against King Ferrante of Aragon swore here to expel the Aragonese from the Kingdom of Naples. The present church was built in the 16th century and expanded over the following two centuries: the nave was widened from one to three aisles, and the impressive bell tower was erected, which still dominates Lacedonia\'s historic skyline. These works gave the building the grandeur and solemnity typical of Southern Italian Baroque ecclesiastical architecture. The interior preserves frescoes, sacred artworks and furnishings of considerable quality, severely damaged by the 1980 earthquake and subsequently restored. The church has been digitized into a navigable 3D model allowing visitors to admire the details of frescoes and sacred furnishings up close.',
        'tags'       => 'cattedrale,Chiesa Madre,barocco,XVI secolo,Ferrante d\'Aragona,Congiura dei Baroni,campanile,arte sacra,terremoto 1980',
    ],

    [
        'id'         => 'cappella-santissima-trinita',
        'borough_id' => 'lacedonia',
        'category'   => 'Patrimonio Religioso',
        'sort_order' => 24,
        'name_it'    => 'Cappella della Santissima Trinità',
        'name_en'    => 'Chapel of the Holy Trinity',
        'desc_it'    => 'La Cappella della Santissima Trinità è uno dei luoghi di culto più antichi e ricchi di storia di Lacedonia. La sua importanza storica è testimoniata da una scoperta eccezionale: all\'interno della cappella, il religioso e ricercatore locale Pasquale Palmese rinvenne un\'epigrafe latina appartenente a Lucio Licinio, discendente di Marco Licinio Magro, membro della tribù Galeria di Roma — prova concreta dell\'esistenza di un insediamento romano nel territorio lacedoniese. L\'edificio attuale non è quello originario: i numerosi terremoti che hanno colpito l\'area hanno distrutto la chiesa primitiva. Nel 1600, il vescovo La Morea ne dispose la ricostruzione ex novo. Sul portone d\'ingresso in pietra si leggono due lastre con iscrizioni latine: "SANCTA TRINITAS VNVS DEVS MISERERE NOBIS" e un\'iscrizione datata al vescovo che sovrintese ai lavori. Compromessa nuovamente dal sisma del 23 novembre 1980, la cappella fu riaperta ai fedeli solo nel luglio 2002. Il legame con San Gerardo Maiella aggiunge un ulteriore strato di spiritualità: il santo avrebbe cacciato il demonio in questo luogo dopo averlo seguito a Lacedonia in una notte di tempesta. Dal 2010, un grande dipinto su ceramica sulla parete esterna commemora questo evento. La Festa della Santissima Trinità, nella prima decade di giugno, anima la comunità con giochi tradizionali e momenti di aggregazione.',
        'desc_en'    => 'The Chapel of the Holy Trinity is one of Lacedonia\'s oldest and most historically significant places of worship. Its historical importance is attested by an exceptional discovery: local priest and researcher Pasquale Palmese found inside the chapel a Latin inscription belonging to Lucius Licinius, descendant of Marcus Licinius Mager, a member of the Roman Galeria tribe — concrete proof of the existence of a Roman settlement in the Lacedonian territory. The current building is not the original: the numerous earthquakes that have struck the area destroyed the primitive church. In 1600 Bishop La Morea ordered its complete reconstruction. On the stone entrance doorway, two slabs bear Latin inscriptions: "SANCTA TRINITAS VNVS DEVS MISERERE NOBIS" and an inscription referencing the bishop who oversaw the works. Damaged again by the earthquake of 23 November 1980, the chapel was reopened to the faithful only in July 2002. A further layer of spirituality is added by the connection to San Gerardo Maiella, who according to tradition expelled the devil from this place after having been forced to follow him to Lacedonia on a stormy night. Since 2010, a large ceramic painting on the external wall commemorates this event. The Feast of the Holy Trinity, held in the first decade of June, enlivens the community with traditional games and moments of togetherness.',
        'tags'       => 'Santissima Trinità,epigrafe romana,San Gerardo Maiella,XVII secolo,terremoto 1980,festa,iscrizioni latine,storia ecclesiastica',
    ],

    /* ─── NATURA ─────────────────────────────────────────────────────── */

    [
        'id'         => 'fontane-storiche',
        'borough_id' => 'lacedonia',
        'category'   => 'Arredo Urbano Storico',
        'sort_order' => 25,
        'name_it'    => 'Fontane Storiche di Lacedonia',
        'name_en'    => 'Historic Fountains of Lacedonia',
        'desc_it'    => 'Lacedonia conserva tre fontane storiche che testimoniano secoli di vita urbana e del rapporto tra la comunità e l\'acqua: la Fontana di Santa Maria della Consolazione, la Fontana Vecchia e la Fontana Serre. Queste strutture idrauliche, costruite in pietra calcarea locale con vasche e decorazioni di pregio, hanno svolto per generazioni un ruolo che andava ben oltre il semplice approvvigionamento idrico. Erano luoghi di socialità, incontro e scambio: le donne vi si ritrovavano a lavare i panni, i viandanti vi si fermavano a dissetarsi, i pastori vi abbeveravano le greggi durante la transumanza. La Fontana Vecchia, come suggerisce il nome, è presumibilmente la più antica delle tre; la Fontana di Santa Maria della Consolazione, associata all\'omonima chiesa, potrebbe avere origini medievali; la Fontana Serre, situata in un\'area un tempo periferica, era probabilmente cruciale per le attività agricole delle contrade. Disseminati nel paesaggio urbano e rurale, si trovano anche numerose pile — vasche in pietra di dimensioni minori che testimoniavano l\'ingegnosità nella distribuzione idrica di epoche in cui ogni fonte era una risorsa preziosa. Il progetto MetaBorghi ha documentato le fontane con fotografie sferiche a 360°, creando un percorso virtuale tra questi testimoni lapidei dell\'identità idrica di Lacedonia.',
        'desc_en'    => 'Lacedonia preserves three historic fountains that testify to centuries of urban life and the relationship between the community and water: the Fontana di Santa Maria della Consolazione, the Fontana Vecchia and the Fontana Serre. These hydraulic structures, built in local limestone with decorative basins, served for generations a role that went far beyond simple water supply. They were places of sociability, encounter and exchange: women gathered there to do the laundry, travellers stopped to quench their thirst, shepherds watered their flocks during transhumance. The Fontana Vecchia (Old Fountain), as its name suggests, is presumably the oldest of the three; the Fontana di Santa Maria della Consolazione, associated with the church of the same name, may have medieval origins; the Fontana Serre, located in what was once a peripheral area, was probably crucial for the agricultural activities of the outlying districts. Scattered throughout the urban and rural landscape are also numerous pile — smaller stone basins that testify to the ingenuity of water distribution in an era when every spring was a precious resource. The MetaBorghi project has documented the fountains with 360° spherical photographs, creating a virtual itinerary between these stone witnesses to Lacedonia\'s water heritage.',
        'tags'       => 'fontane,acqua,pietra calcarea,arredo urbano,transumanza,storia sociale,Fontana Vecchia,Fontana Serre',
    ],

    [
        'id'         => 'capi-dell-acqua',
        'borough_id' => 'lacedonia',
        'category'   => 'Natura e Ambiente',
        'sort_order' => 26,
        'name_it'    => 'Capi dell\'Acqua',
        'name_en'    => 'Capi dell\'Acqua',
        'desc_it'    => 'A breve distanza dal centro storico di Lacedonia si nasconde uno degli angoli naturali più preziosi dell\'Irpinia orientale: Capi dell\'Acqua, una sorgente naturale di rara bellezza immersa in una vegetazione rigogliosa. Il nome stesso — "Capi dell\'Acqua" — rispecchia le numerose sorgenti di acqua fresca che sgorgano dalle rocce calcaree, formando ruscelli cristallini che attraversano boschi di querce e castagni secolari. L\'area è un ecosistema di eccezionale biodiversità: numerose specie di uccelli e anfibi trovano qui il loro habitat naturale, rendendo il sito una meta privilegiata per il birdwatching e l\'osservazione naturalistica. I sentieri che si snodano tra le sorgenti permettono escursioni accessibili anche alle famiglie, con un percorso immerso nella natura incontaminata dell\'Appennino campano-lucano. Il significato di Capi dell\'Acqua non è solo naturalistico: dalla preistoria — quando le grotte tufacee del territorio erano già abitate da oltre 13.000 anni fa — fino all\'epoca romana e alle vicende del brigantaggio postunitario, queste sorgenti hanno rappresentato una risorsa vitale per le popolazioni locali. Oggi potrebbero diventare il fulcro di un\'offerta di turismo lento e sostenibile, con percorsi guidati, attività di educazione ambientale e un modello di valorizzazione che tenga insieme storia, natura e comunità. Il tour virtuale MetaBorghi documenta l\'area in un\'esperienza immersiva a 360°.',
        'desc_en'    => 'A short distance from Lacedonia\'s historic centre lies one of eastern Irpinia\'s most precious natural corners: Capi dell\'Acqua, a natural spring of rare beauty immersed in lush vegetation. The name itself — "Capi dell\'Acqua" (Headwaters) — reflects the numerous freshwater springs that emerge from the limestone rocks, forming crystal-clear streams that flow through ancient oak and chestnut forests. The area is an ecosystem of exceptional biodiversity: numerous species of birds and amphibians find their natural habitat here, making the site a favoured destination for birdwatching and nature observation. The paths that wind between the springs allow hikes accessible to families, immersed in the pristine nature of the Campano-Lucanian Apennines. The significance of Capi dell\'Acqua is not only naturalistic: from prehistory — when the tuff caves of the territory were already inhabited over 13,000 years ago — through the Roman period and the episodes of post-unification brigandage, these springs have represented a vital resource for local populations. Today they could become the focal point of a slow and sustainable tourism offer, with guided trails, environmental education activities and a model of valorisation that brings together history, nature and community. The MetaBorghi virtual tour documents the area in an immersive 360° experience.',
        'tags'       => 'sorgente,natura,biodiversità,birdwatching,trekking,Appennino,querce,castagni,turismo lento,acqua',
    ],

];

// Esegui upsert
foreach ($pois as $poi) {
    upsertPoi($db, $poi, $results, $errors);
}

$pageTitle = 'Seed POI Lacedonia — Completo';
require '_layout.php';
?>
<div class="flex-1 overflow-auto p-6">
<div class="max-w-3xl mx-auto">

<h2 class="text-2xl font-bold text-white mb-2">&#127963; Seed POI Lacedonia — Completo</h2>
<p class="text-slate-400 text-sm mb-6">Carica <?= count($pois) ?> Punti di Interesse con testi IT+EN. Usa ON DUPLICATE KEY UPDATE: eseguibile più volte.</p>

<div class="bg-slate-800 rounded-2xl border border-slate-700 p-5 mb-6">
  <?php foreach ($results as $r): ?>
    <div class="py-1 text-emerald-400 text-sm font-mono"><?= htmlspecialchars($r) ?></div>
  <?php endforeach; ?>
  <?php foreach ($errors as $e): ?>
    <div class="py-1 text-red-400 text-sm font-mono"><?= htmlspecialchars($e) ?></div>
  <?php endforeach; ?>
</div>

<div class="bg-slate-800 rounded-2xl border border-slate-700 p-5 mb-6">
  <p class="text-white text-sm font-semibold mb-1">Riepilogo</p>
  <p class="text-slate-300 text-sm">Inseriti/aggiornati: <strong class="text-emerald-400"><?= count($results) ?></strong> &nbsp;|&nbsp; Errori: <strong class="text-red-400"><?= count($errors) ?></strong></p>
</div>

<div class="flex flex-wrap gap-3">
  <a href="punti-interesse.php?borough=lacedonia" class="bg-emerald-600 hover:bg-emerald-500 text-white text-sm font-semibold px-4 py-2 rounded-lg">&#128196; Gestisci POI in admin</a>
  <a href="/borghi/lacedonia/" class="bg-cyan-700 hover:bg-cyan-600 text-white text-sm font-semibold px-4 py-2 rounded-lg" target="_blank">&#127758; Vedi Lacedonia ↗</a>
</div>

</div>
</div>
<?php require '_footer.php'; ?>
